Варіант №21

Посилання на Github: https://github.com/DSviatenko/machine-learning

In [37]:
import numpy as np

1. Створіть одновимірний масив (вектор) з оберненими значеннями натуральних чисел, починаючи з 1, та виведіть його значення. 

In [38]:
vector = []

for i in range(1, 11):
    vector.append(1 / i)
    
print(vector)

[1.0, 0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111, 0.1]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його косинусами кожного натурального числа, починаючи з 1, та виведіть його значення. 

In [39]:
matrix = np.empty((3, 3))
number = 1

for i in range(0, 3):
    for j in range(0, 3):
        matrix[i, j] = np.cos(number)
        number += 1

print(matrix)

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


3. Створіть масив розміром 7x7, заповніть його випадковими цілими числами від -50 до 50 та знайдіть відсоток непарних чисел серед додатних елементів

In [40]:
array = np.random.randint(-50, 51, size=(7, 7))
pos_numbers = 0
odd_pos_numbers = 0

for i in range(0, 7):
    for j in range(0, 7):
        if array[i, j] > 0 :
            pos_numbers += 1
            if array[i, j] % 2 == 1:
                odd_pos_numbers += 1

print(array, "- matrix")
print(odd_pos_numbers * 100 / pos_numbers, "%")

[[  0 -40  28  33 -30  -8  31]
 [-45   1 -40  43  18 -32 -32]
 [  3 -31 -47  41  28   6 -12]
 [-19 -16  13 -36   8 -22  -1]
 [-39  -9 -13 -36 -28  24  15]
 [ 36 -28 -47 -49   7  25  -1]
 [-19   9 -41 -17  27  32  28]] - matrix
57.142857142857146 %


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від -0.7 до 0.7 та виведіть його значення. 

In [41]:
array = np.random.uniform(-0.7, 0.7, (4,4))
print(array)

[[ 0.02770468 -0.49928016  0.43109797 -0.01338197]
 [-0.26304016  0.48561467  0.12299695 -0.47709184]
 [ 0.09209677 -0.62627573 -0.03121326 -0.46735638]
 [ 0.42705334  0.69704721  0.1442488   0.0104988 ]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 10 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [42]:
a = np.random.randint(10, 20, size=5)
b = np.random.randint(10, 20, size=5)

print(a)
print(b)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

[13 17 17 13 16]
[10 14 18 19 11]
a =  [13 17 17 13 16]
b =  [10 14 18 19 11]
a + b =  [23 31 35 32 27]
a - b =  [ 3  3 -1 -6  5]
a * b =  [130 238 306 247 176]


6. Створіть два вектори розміром 6, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток. 

In [43]:
a = np.random.uniform(1, 20, size=7)
b = np.random.uniform(1, 20, size=7)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("result =", dot_a_b)

a =  [ 5.02735294 17.52636354 14.14949084 12.23717814  3.54550188  1.6944946
 14.35512702]
b =  [ 4.01220192 18.93444444  6.7906849   6.51382301  5.50909646  8.50338923
  4.79070063]
result = 630.5308330533934


7. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [44]:
a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(1, 10, size=(3, 3))

dot_a_b = np.dot(a, b)

print("a:")
print(a)
print("b:")
print(b)
print("result:")
print(dot_a_b)

a:
[[1 7 9]
 [5 2 9]]
b:
[[6 6 7]
 [7 8 3]
 [8 9 2]]
result:
[[127 143  46]
 [116 127  59]]


8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю. 

In [45]:
matrix = np.random.randint(1, 13, size=(2, 2))

print("matrix:")
print(matrix)

if np.linalg.det(matrix) == 0:
    print("matrix contains 0")
else:
    inv_matrix = np.linalg.inv(matrix)
    print("result:")
    print(inv_matrix)

matrix:
[[ 4 11]
 [ 2  8]]
result:
[[ 0.8 -1.1]
 [-0.2  0.4]]


9. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її

In [46]:
matrix = np.random.rand(3, 3)
print("matrix")
print(matrix)

trans_matrix = np.transpose(matrix)
print("result:")
print(trans_matrix)

matrix
[[0.39366884 0.01426745 0.74045413]
 [0.19109496 0.92979754 0.88131589]
 [0.40054745 0.64918405 0.703881  ]]
result:
[[0.39366884 0.19109496 0.40054745]
 [0.01426745 0.92979754 0.64918405]
 [0.74045413 0.88131589 0.703881  ]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму добутків елементів кожного рядка матриці на відповідний елемент вектору

In [47]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.rand(4)
print("matrix:")
print(matrix)
print("vector:")
print(vector)

print("result:")
result = np.sum(matrix * vector, axis=1)
print(result)

matrix:
[[3 4 8 1]
 [2 7 4 5]
 [8 4 1 6]]
vector:
[0.37786193 0.35258266 0.97400133 0.96989519]
result:
[11.30582225 11.96928375 11.22659859]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор. 

In [48]:
matrix = np.random.rand(2, 3)
vector = np.random.randint(1, 10, size=3)
print("matrix:")
print(matrix)
print("vector:")
print(vector)

print("result:")
result = np.dot(matrix, vector)
print(result)

matrix:
[[0.76225208 0.01272372 0.31650362]
 [0.66168435 0.71069491 0.94225604]]
vector:
[2 6 9]
result:
[ 4.44937907 14.06784256]


12. Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів першої матриці. 

In [49]:
matrix1 = np.random.randint(1, 11, size=(6, 6))

print("first matrix:")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(6, 6))

print("second matrix:")
print(matrix2)

sum_of_elements = np.sum(matrix1)

# Виводимо суму
print("sum first matrix:", sum_of_elements)

first matrix:
[[ 1  5  8  5  9 10]
 [ 8  2  8  7  9  6]
 [ 3  8 10  1 10  2]
 [ 7  6  4  1  1  3]
 [ 4  2  9 10  3  7]
 [ 7  3  9  3  6  2]]
second matrix:
[[4 5 1 4 6 8]
 [1 2 4 7 1 7]
 [9 4 4 2 1 3]
 [6 9 9 4 3 8]
 [5 1 9 5 1 8]
 [4 9 7 3 1 7]]
sum first matrix: 199


13. Створіть дві матриці розміром 5x5, заповніть їх випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть добуток їх елементів. 

In [50]:
matrix1 = np.random.uniform(-2, 2, size=(5, 5))
matrix2 = np.random.uniform(-2, 2, size=(5, 5))

print("first matrix:")
print(matrix1)
print("second matrix:")
print(matrix2)

product = np.prod(matrix1) * np.prod(matrix2)

print("result:", product)

first matrix:
[[ 1.11573161 -0.3943107  -1.43311647  1.51974422  0.04227155]
 [ 0.02390264  1.07966898  1.58245429 -1.06695336 -0.8815568 ]
 [ 0.63044407  1.41431036  0.40657907 -1.32941828 -1.28052244]
 [ 1.88239779  0.09292324  0.8993812   1.16141653 -1.76794105]
 [ 0.08134484  1.36601012 -0.82654164  1.69893496 -1.62083106]]
second matrix:
[[-1.31295648  1.85762013  1.57754493 -1.7236323   1.7127849 ]
 [-0.57290115  1.45627104 -0.35929165  0.9235163   1.36015861]
 [-0.30105394  1.74785328 -1.40032133 -0.87495572 -1.97479126]
 [-0.07756564 -0.39091737 -1.21131615 -0.64570297  1.58330249]
 [ 0.79688813 -1.77756218 -1.21218639  0.58884174 -0.2516972 ]]
result: 4.081750722304153e-06


14. Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть найменший елемент матриці

In [51]:
matrix = np.random.uniform(-10, 10, size=(7, 7))

print("matrix:")
print(matrix)

min_element = np.min(matrix)

print("result:", min_element)

matrix:
[[-3.41005127  6.81732311  6.34549326  4.10953154 -6.40960063 -2.76036337
  -0.66852575]
 [-4.51333605  0.66746967 -6.27360674 -6.36982949  8.73216231  6.0470862
   3.96280001]
 [-0.64322269 -0.49667064  6.94395766 -0.01064689 -0.0131901   0.98904065
  -5.12765254]
 [-5.14010263  3.65427925  6.06855252  7.50001204  1.84626289 -7.35803956
  -8.19945277]
 [-6.63844419  1.97632079 -2.36016433  5.83830345  4.75652291  1.60876327
  -2.45343659]
 [ 3.85339647  8.04841367  3.22231951 -8.96212086  3.36029306 -1.29274331
  -7.12980661]
 [ 1.14303117 -6.98523838 -2.40959412 -3.26568064  8.55979664  6.93052605
  -2.72247415]]
result: -8.962120855350864


15. Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці

In [52]:
matrix = np.random.rand(7, 7)

print("matrix:")
print(matrix)

column_sums = np.sum(matrix, axis=0)

col_vec = column_sums.reshape((-1, 1))

print("result:")
print(col_vec)

matrix:
[[0.90551627 0.03893368 0.6912607  0.93710469 0.17590675 0.09080383
  0.98415359]
 [0.53532779 0.10781069 0.46474866 0.21961238 0.01898854 0.82390628
  0.9403028 ]
 [0.80703679 0.86487095 0.7169153  0.72237752 0.54681593 0.87354424
  0.75018729]
 [0.68683229 0.20814738 0.78084307 0.12638651 0.6807596  0.98022426
  0.46070368]
 [0.03466058 0.90682145 0.1054248  0.74157533 0.61102005 0.01543623
  0.74267581]
 [0.10763965 0.97435552 0.87961114 0.68330181 0.20325949 0.24789778
  0.20089193]
 [0.50956337 0.20495351 0.98350899 0.69349482 0.48808795 0.89510635
  0.1330229 ]]
result:
[[3.58657675]
 [3.30589318]
 [4.62231266]
 [4.12385307]
 [2.72483833]
 [3.92691896]
 [4.211938  ]]


***Висновок:*** *на практичній роботі я поглибив знання з мови програмування Python, використовуючи бібліотеку "numpy". Протягом роботи я виконував різні завдання зі створення, додавання, віднімання, множення матриць та векторів, а також їх елементів.*